parameters:
  databricksbundle:
    databricks_connect:
      connection:
        address: 'https://westeurope.azuredatabricks.net'
        token: 'abcd123456'
        cluster_id: '0416-084917-doles835'
        org_id: 123456789
