parameters:
  databricksbundle:
    databricks_connect:
      connection:
        address: 'https://dbc-123.cloud.databricks.com'
        token: 'abcd123456'
        cluster_id: '0416-084917-doles835'
